Adding options

diff --git a/ssl_mitm/ssl_mitm b/ssl_mitm/ssl_mitm
--- a/ssl_mitm/ssl_mitm
+++ b/ssl_mitm/ssl_mitm
@@ -1,15 +1,59 @@
 #!/usr/bin/env bash
 
 FILENAME=socat
-
 LOCAL_PORT=4443
 REMOTE_HOST=www.google.com
 REMOTE_PORT=443
+TOR=false
+SUDO=false
 
-if [ ! -f $FILENAME.pem ]; then
-    openssl genrsa -out $FILENAME.key 1024
-    openssl req -new -key $FILENAME.key -x509 -days 3653 -out $FILENAME.crt
-    cat $FILENAME.key $FILENAME.crt >$FILENAME.pem
+while getopts 'P:d:p:hts' flag; do
+    case "${flag}" in
+        h)
+            echo "Usage:"
+            echo "-h    show brief help"
+            echo "-P    port to listen on       Default: $LOCAL_PORT"
+            echo "-d    host to connnect to     Default: $REMOTE_HOST"
+            echo "-p    port to connect to      Default: $REMOTE_PORT"
+            echo "-s    run with sudo           Default: $SUDO"
+            echo "-t    use tor connect         Default: $TOR"
+            exit 0
+            ;;
+        P) LOCAL_PORT=${OPTARG} ;;
+        d) REMOTE_HOST=${OPTARG} ;;
+        p) REMOTE_PORT=${OPTARG} ;;
+        s) SUDO=true ;;
+        t) TOR=true ;;
+    esac
+done
+
+CMD="socat -v -x openssl-listen:$LOCAL_PORT,reuseaddr,cert=$PWD/$FILENAME.pem,cafile=$PWD/$FILENAME.crt,verify=0 openssl-connect:$REMOTE_HOST:$REMOTE_PORT,verify=0"
+
+
+if [ $TOR == true ]; then
+    CMD="proxychains $CMD"
+fi
+if [ $SUDO == true ]; then
+    CMD="sudo $CMD"
+fi
+if [ $LOCAL_PORT -lt 1024 ]; then
+    if [ $SUDO == false ]; then
+        echo "sudo required for listening on ports below 1024"
+        exit
+    fi
 fi
 
-socat -v -x openssl-listen:$LOCAL_PORT,reuseaddr,cert=$PWD/$FILENAME.pem,cafile=$PWD/$FILENAME.crt,verify=0 openssl-connect:$REMOTE_HOST:$REMOTE_PORT,verify=0
+if [ ! -f $FILENAME.pem ]; then
+    openssl genrsa -out $FILENAME.key 2048
+    openssl req -new -key $FILENAME.key -x509 -days 365 -out $FILENAME.crt
+    cat $FILENAME.key $FILENAME.crt >$FILENAME.pem
+    openssl dhparam -out dhparams.pem 2048
+    cat dhparams.pem >> $FILENAME.pem
+fi
+
+while [ true ]; do
+    echo $CMD
+    $CMD
+
+    test $? -gt 128 && break
+done
